/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BButton: typeof import('bootstrap-vue-next/components/BButton')['BButton']
    BCard: typeof import('bootstrap-vue-next/components/BCard')['BCard']
    BCardText: typeof import('bootstrap-vue-next/components/BCard')['BCardText']
    BCarousel: typeof import('bootstrap-vue-next/components/BCarousel')['BCarousel']
    BCarouselSlide: typeof import('bootstrap-vue-next/components/BCarousel')['BCarouselSlide']
    BCol: typeof import('bootstrap-vue-next/components/BContainer')['BCol']
    BContainer: typeof import('bootstrap-vue-next/components/BContainer')['BContainer']
    BRow: typeof import('bootstrap-vue-next/components/BContainer')['BRow']
    BTable: typeof import('bootstrap-vue-next/components/BTable')['BTable']
    BTableSimple: typeof import('bootstrap-vue-next/components/BTable')['BTableSimple']
    BTh: typeof import('bootstrap-vue-next/components/BTable')['BTh']
    BThead: typeof import('bootstrap-vue-next/components/BTable')['BThead']
    BTr: typeof import('bootstrap-vue-next/components/BTable')['BTr']
    Desktop: typeof import('./src/components/Desktop.vue')['default']
    Entrypoint: typeof import('./src/components/entrypoint.vue')['default']
    Mobile: typeof import('./src/components/Mobile.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
